"""empty message

Revision ID: 7b58a1312ad8
Revises: 7d5bbb7ea58d
Create Date: 2021-04-26 20:58:39.978870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b58a1312ad8'
down_revision = '7d5bbb7ea58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRegister', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'UserRegister', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserRegister', type_='unique')
    op.drop_column('UserRegister', 'timestamp')
    # ### end Alembic commands ###
