"""empty message

Revision ID: 7d5bbb7ea58d
Revises: d5f6a5095525
Create Date: 2020-12-22 21:27:57.822757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d5bbb7ea58d'
down_revision = 'd5f6a5095525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRegister',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('m', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'UserAuth', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserAuth', type_='unique')
    op.drop_table('UserRegister')
    # ### end Alembic commands ###
